#!/bin/sh

# Protect pre-defined branches from accidental pushes.
echo -e "===\n>> Pre-push Hook:: Checking protected branches and current branch name..."

PROTECTED_BRANCHES="^(master)$"
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if [[ "$BRANCH_NAME" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Pushing directly to a protected branch is not allowed! Please create your own branch and submit a Pull Request to 'dev', or commit directly to it.\n" && exit 1
fi

echo -e ">> Finished checking branch name.\n==="

exit 0
